package:
  name: variantkey-src
  version: 5.0.0

source:
  path: ../..

build:
  number: 1

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: VariantKey library C header only source code
