package:
  name: vk
  version: 2.11.3

source:
  path: ../..

build:
  number: 1

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: VariantKey fast encoder command line application
