package:
  name: pyvariantkey
  version: 4.3.0

source:
  path: ../..

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
    - numpy >=1.15.0
  build:
    - {{ compiler('c') }}
    - variantkey >=4.3.0
    - numpy >=1.15.0
  run:
    - python
    - variantkey >=4.3.0
    - numpy >=1.15.0

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pycodestyle
    - variantkey >=4.3.0
    - numpy >=1.15.0
  imports:
    - pyvariantkey

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: Python class wrapper for Genetic VariantKey Library
