package:
  name: variantkey
  version: 3.1.1.1

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-pep8
    - pytest-cov
    - pytest-benchmark
  imports:
    - variantkey

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
