package:
  name: r-variantkey
  version: 2.7.1

source:
  path: ../..

build:
  number: 1

rpaths:
  - lib/R/lib/
  - lib/

requirements:
  host:
    - r-base
    - r-devtools
    - r-roxygen2
    - r-testthat
  build:
    - {{ compiler('c') }}
    - r-inline
    - r-pryr
    - r-Rcpp
  run:
    - r-base

test:
  requires:
    - r-base
    - r-testthat
  imports:
    - variantkey

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: Genetic VariantKey R Library
