package:
  name: vk
  version: 1.0.2.1

source:
  path: ../..

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: VariantKey fast encoder command line application
