package:
  name: variantkey
  version: 2.11.3

source:
  path: ../..

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pycodestyle
  imports:
    - variantkey

about:
  home: https://github.com/genomicsplc/variantkey
  license: MIT
  license_file: LICENSE
  summary: Genetic VariantKey Library
